import React from "react";
import HostedModel from "./HostedModel";

export default function HostedModelSection() {
  return (
    <>
      <section className="fill-in-form w-full bg-green py-40 md:py-60 px-10 md:px-32 lg:px-60 ">
        <div className="container mx-auto mb-32 max-w-xl ">
          <h1 className="text-beige text-lg text-center leading-loose">
            Create a job application generated by a neural network trained on
            Drake lyrics and public resumes.
          </h1>
        </div>

        <HostedModel />
      </section>
    </>
  );
}
