import React from "react";
import { useEffect } from "react";
import HostedModel from "./HostedModel";

export default function HostedModelSection() {
  return (
    <>
      <section
        id="model-section"
        className="fill-in-form w-full bg-green pt-32 pb-20 md:py-60 px-10 md:px-32 lg:px-60 "
      >
        <div className="container mx-auto mb-20 md:mb-32 max-w-xl ">
          <h1 className="text-beige text-md md:text-lg text-center leading-loose">
            Fill in the form and create a job rapplication generated by a neural
            network trained on Drake lyrics and public resumes.
          </h1>
        </div>

        <HostedModel />

        <style jsx>{`
          {
            .model-section {
            opacity: 0;
           transition: all .35s ease-in-out;
          }
          .model-section--inView {
            opacity: 1;
            
          }
      `}</style>
      </section>
    </>
  );
}
