import React from "react";
import HostedModel from "./HostedModel";
import { useInView } from "react-intersection-observer";
import { Helmet } from "react-helmet";

export default function HostedModelSection() {
  const { ref, inView, entry } = useInView({
    threshold: 0.1,
  });

  const bgColor = inView ? "bg-green" : "bg-beige";

  return (
    <>
      <Helmet>
        <body className={`transition duration-1000 ease-in-out ${bgColor}`} />
      </Helmet>
      <section
        id="model-section"
        className={`fill-in-form w-full pt-32 pb-20 md:py-60 px-10 md:px-32 lg:px-60`}
        ref={ref}
      >
        <div className="container mx-auto mb-20 md:mb-32 max-w-xl">
          <h1 className="text-beige text-md text-center leading-loose">
            Fill in the form and create a job rapplication generated by a neural
            network trained on Drake lyrics and public resumes.
          </h1>
        </div>

        <HostedModel />

        <style jsx>{`
          {
            .model-section {
            opacity: 0;
           transition: all .35s ease-in-out;
          }
          .model-section--inView {
            opacity: 1;
            
          }
      `}</style>
      </section>
    </>
  );
}
